name: Biwenger Bidder

on:
  schedule:
    - cron: "0 * * * *"   # cada hora en punto
  workflow_dispatch: {}

jobs:
  run-bidder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: |
          npm ci
          npx playwright install --with-deps chromium

      - name: Run bidder
        env:
          BIWENGER_EMAIL: ${{ secrets.BIWENGER_EMAIL }}
          BIWENGER_PASSWORD: ${{ secrets.BIWENGER_PASSWORD }}
          DRY_RUN: ${{ vars.DRY_RUN || '0' }}
          BID_CAP: ${{ vars.BID_CAP || '0' }}
          HEADLESS: '1'
          CSV_PATH: 'logs/biwenger_bids.csv'
          MAX_OVERPAY_RATIO: ${{ vars.MAX_OVERPAY_RATIO || '1.38' }}
        run: node bid-biwenger.js

      - name: Upload bids CSV
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: biwenger-bids
          path: logs/biwenger_bids.csv
          if-no-files-found: ignore
          retention-days: 30