name: Biwenger Auctions Bot

on:
  schedule:
    - cron: "*/48 * * * *"   # cada 48 minutos (UTC)
  workflow_dispatch:       # permitir lanzarlo a mano

jobs:
  run-bot:
    runs-on: ubuntu-latest
    env:
      X_LANG: es
      X_VERSION: "628"
      MAX_PRICE_MULTIPLIER: "1.5"   # tope 150% del price
      BID_INCREMENT_FACTOR: "1.01"  # +1%
      INCREMENT_THRESHOLD: "60000"
      MAX_AUCTION_HOURS: "2"
      DRY_RUN: "0"                  # "1" para simular sin pujar

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm ci

      - name: Run Biwenger bidding
        env:
          BIWENGER_EMAIL: ${{ secrets.BIWENGER_EMAIL }}
          BIWENGER_PASSWORD: ${{ secrets.BIWENGER_PASSWORD }}
          BIWENGER_LEAGUE_ID: ${{ secrets.BIWENGER_LEAGUE_ID }}
          BIWENGER_USER_ID: ${{ secrets.BIWENGER_USER_ID }}
          X_LANG: ${{ env.X_LANG }}
          X_VERSION: ${{ env.X_VERSION }}
          MAX_PRICE_MULTIPLIER: ${{ env.MAX_PRICE_MULTIPLIER }}
          BID_INCREMENT_FACTOR: ${{ env.BID_INCREMENT_FACTOR }}
          MAX_AUCTION_HOURS: ${{ env.MAX_AUCTION_HOURS }}
          DRY_RUN: ${{ env.DRY_RUN }}
        run: node src/index.js
