name: Biwenger Bot

on:
  schedule:
    - cron: "0 * * * *"   # cada hora, en el minuto 0
  workflow_dispatch:       # ejecución manual opcional

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm ci
          npx playwright install --with-deps chromium

      - name: Run Biwenger bot
        env:
          DRY_RUN: "0"           # pon "1" si quieres simular
          BID_CAP: "5"           # máximo de pujas por ejecución (0 = sin límite)
          HEADLESS: "1"          # en CI siempre headless
        run: node bid-biwenger.js

